# 2. Matrix Multiplication in PyTorch

Matrix multiplication is essential for neural networks!
PyTorch provides efficient operations for multiplying matrices and tensors.


In [2]:
import torch

## 1. Matrix Multiplication (@ operator)

Use the @ operator or torch.matmul() for matrix multiplication!
A @ B multiplies matrices A and B.


In [3]:
# Create two matrices
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print(f"Shape: {A.shape}")
print()

print("Matrix B:")
print(B)
print(f"Shape: {B.shape}")
print()

# Matrix multiplication using @
result = A @ B
print("A @ B (matrix multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# Using torch.matmul()
result2 = torch.matmul(A, B)
print("torch.matmul(A, B):")
print(result2)
print("(Same result!)")


Matrix A:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])
Shape: torch.Size([2, 2])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])
Shape: torch.Size([2, 2])

torch.matmul(A, B):
tensor([[19., 22.],
        [43., 50.]])
(Same result!)


## 2. Matrix-Vector Multiplication

Multiply a matrix by a vector to transform it!


In [3]:
# Matrix-vector multiplication
M = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

v = torch.tensor([5, 6], dtype=torch.float32)

print("Matrix M:")
print(M)
print(f"Shape: {M.shape}")
print()

print("Vector v:")
print(v)
print(f"Shape: {v.shape}")
print()

# Matrix × Vector
result = M @ v
print("M @ v (matrix-vector multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# How it works
print("How it works:")
print(f"Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = {M[0, 0]}*{v[0]} + {M[0, 1]}*{v[1]} = {result[0]}")
print(f"Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = {M[1, 0]}*{v[0]} + {M[1, 1]}*{v[1]} = {result[1]}")


Matrix M:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Vector v:
tensor([5., 6.])
Shape: torch.Size([2])

M @ v (matrix-vector multiplication):
tensor([17., 39.])
Shape: torch.Size([2])

How it works:
Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = 1.0*5.0 + 2.0*6.0 = 17.0
Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = 3.0*5.0 + 4.0*6.0 = 39.0


## 3. Batch Matrix Multiplication

Process multiple matrices at once using batch dimensions!
Very useful for neural networks!


In [6]:
# Batch matrix multiplication
# Create batch of matrices: (batch_size, rows, cols)
batch_A = torch.randn(3, 2, 4)  # 3 matrices, each 2×4
batch_B = torch.randn(3, 4, 3)  # 3 matrices, each 4×3

print("Batch A (3 matrices, each 2×4):")
print(batch_A)
print(f"Shape: {batch_A.shape}")
print()

print("Batch B (3 matrices, each 4×3):")
print(batch_B)
print(f"Shape: {batch_B.shape}")
print()

# Batch matrix multiplication
batch_result = torch.bmm(batch_A, batch_B)
print("Batch matrix multiplication result:")
print(batch_result)
print(f"Shape: {batch_result.shape}")
print("(3 matrices, each 2×3)")
print()

# Verify: first matrix multiplication
A0 = batch_A[0]
B0 = batch_B[0]
result0 = A0 @ B0

print("First matrix multiplication (manual):")
print(result0)
print()

print("First matrix multiplication (from batch):")
print(batch_result[0])
print("(Should match!)")
print(f"Are they equal? {torch.allclose(result0, batch_result[0])}")


Batch A (3 matrices, each 2×4):
tensor([[[-1.0043, -0.4849, -0.8475,  1.3237],
         [ 0.0374,  0.3003,  0.9164, -0.0794]],

        [[ 0.7269,  0.4505,  1.3375,  0.6164],
         [ 0.3549,  0.3345, -0.7236, -0.6826]],

        [[ 1.2891, -0.5808,  0.7336, -0.5988],
         [-0.4093, -0.4510,  0.1952,  0.9642]]])
Shape: torch.Size([3, 2, 4])

Batch B (3 matrices, each 4×3):
tensor([[[ 0.6137,  0.4694, -0.6191],
         [-1.2483, -0.9596,  0.3200],
         [-0.8753,  1.3120,  0.0802],
         [ 0.6633,  0.9255, -1.3049]],

        [[ 0.9112, -1.1908, -2.6773],
         [ 1.0528, -0.5387, -0.7989],
         [ 1.6482, -0.4867,  2.2498],
         [ 0.9685, -0.0758,  1.1678]],

        [[-0.4030, -0.0820,  0.1043],
         [-1.0523,  0.0421, -0.6743],
         [ 0.9280,  0.2208,  0.6413],
         [ 0.0280, -0.4017,  0.0772]]])
Shape: torch.Size([3, 4, 3])

Batch matrix multiplication result:
tensor([[[ 1.6086,  0.1070, -1.3287],
         [-1.2067,  0.8583,  0.2500]],

        [[ 3

## 4. Element-wise Multiplication

Multiply elements at the same position (not matrix multiplication)!
Use * for element-wise multiplication.


In [5]:
# Element-wise multiplication (different from matrix multiplication!)
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

# Element-wise multiplication
element_wise = A * B
print("A * B (element-wise multiplication):")
print(element_wise)
print()

# Matrix multiplication (for comparison)
matrix_mult = A @ B
print("A @ B (matrix multiplication):")
print(matrix_mult)
print()

print("Notice: Element-wise (*) is different from matrix multiplication (@)!")
print(f"Element-wise: {A[0, 0]} * {B[0, 0]} = {element_wise[0, 0]}")
print(f"Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = {matrix_mult[0, 0]}")


Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])

A * B (element-wise multiplication):
tensor([[ 5., 12.],
        [21., 32.]])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])

Notice: Element-wise (*) is different from matrix multiplication (@)!
Element-wise: 1.0 * 5.0 = 5.0
Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = 19.0
